apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devopsledger.fullname" . }}-web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: {{ include "devopsledger.fullname" . }}-web
  template:
    metadata:
      labels:
        app: {{ include "devopsledger.fullname" . }}-web
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.web.repository }}:{{ .Values.image.web.tag }}"
          imagePullPolicy: {{ .Values.image.web.pullPolicy }}
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: {{ include "devopsledger.fullname" . }}-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devopsledger.fullname" . }}-web
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: 3000
  selector:
    app: {{ include "devopsledger.fullname" . }}-web
